# Generated by Django 3.2.4 on 2024-01-19 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_job_job_type'),
        ('accounts', '0003_alter_usertips_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertips',
            name='job_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.category'),
        ),
        migrations.AlterField(
            model_name='usertips',
            name='userType',
            field=models.CharField(choices=[('Employer', 'Employer'), ('Employee', 'Employee')], max_length=20),
        ),
    ]
