# Generated by Django 3.2.4 on 2024-01-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Remotly', 'Remotly'), ('Part Time', 'Part Time'), ('Internship', 'Internship')], max_length=50),
        ),
    ]
